car_sales_website/author/urls.py
from django.urls import path
from . import views

app_name='author'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/',views.UserLogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('profile/edit/pass_change/', views.pass_change, name='pass_change'),
]

car_sales_website/car/urls.py
from django.urls import path
from . import views

app_name = 'car'
urlpatterns = [
    path('details/<int:id>/', views.CarDetailView.as_view(), name='car_details'),
    path('buy/<int:id>/', views.buy_now, name='buy_now'),
]

car_sales_website/car_sales_website/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name ='home'),
    path('brand/<slug:brand_slug>/', views.home, name='brand_car'),
    path('author/', include('author.urls')),
    path('car/', include('car.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

car_sales_website/author/models.py
from django.db import models

car_sales_website/brand/models.py
from django.db import models

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True, null=True, blank=True)
    
    def __str__(self):
        return self.name

car_sales_website/car/models.py
from django.db import models
from brand.models import Brand
from django.contrib.auth.models import User
# Create your models here.
class Car(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.FloatField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE) 
    image = models.ImageField(upload_to='car/media/uploads/', blank = True, null = True)
    def __str__(self):
        return self.name
    

class Comment(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=30)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True) 
    
    def __str__(self):
        return f"Comments by {self.name}"
    
class userPurchase(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    quantity_purchased = models.IntegerField()
    total_price = models.FloatField()

    def __str__(self):
        return f"{self.author.username} purchased {self.quantity_purchased} {self.car.name}"

car_sales_website/author/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'id' : 'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'id' : 'required'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ChangeUserForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

car_sales_website/car/forms.py
from django import forms
from .models import  Comment


class CommentForm(forms.ModelForm):
    class Meta: 
        model = Comment
        fields = ['name', 'email', 'body']

car_sales_website/author/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth.forms import  PasswordChangeForm
from django.contrib.auth import  update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from car.models import Car
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from car.models import userPurchase

# Create your views here.

def register(request):
    if request.method == 'POST':
        register_form = forms.RegistrationForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            messages.success(request, 'Account Created Successfully')
            return redirect('author:login')
    
    else:
        register_form = forms.RegistrationForm()
    return render(request, 'register.html', {'form' : register_form, 'type' : 'Signup'})



class UserLoginView(LoginView):
    template_name = 'register.html'
    def get_success_url(self):
        return reverse_lazy('home')
    def form_valid(self, form):
        messages.success(self.request, 'Logged in Successful')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.success(self.request, 'Logged in information incorrect')
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'Login'
        return context

@login_required
def profile(request):
    data = userPurchase.objects.filter(author = request.user)
    return render(request, 'profile.html',{'data':data})


    

@login_required
def edit_profile(request):
    if request.method == 'POST':
        profile_form = forms.ChangeUserForm(request.POST, instance = request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile Updated Successfully')
            return redirect('author:profile')
    
    else:
        profile_form = forms.ChangeUserForm(instance = request.user)
    return render(request, 'update_profile.html', {'form' : profile_form})



@login_required
def pass_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Updated Successfully')
            update_session_auth_hash(request, form.user)
            return redirect('author:profile')
    
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'pass_change.html', {'form' : form})

class UserLogoutView(LogoutView):
    def get_success_url(self):
        return reverse_lazy('home')

car_sales_website/brand/views.py
from django.shortcuts import render

car_sales_website/car/views.py
from django.shortcuts import render,redirect
from . import models
from . import forms
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
# Create your views here.

class CarDetailView(DetailView):
    model = models.Car
    pk_url_kwarg = 'id'
    template_name = 'car_details.html'

    def post(self, request, *args, **kwargs):
        comment_form = forms.CommentForm(data=self.request.POST)
        car = self.get_object()
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.car = car
            new_comment.save()
        return self.get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = self.object 
        comments = car.comments.all()
        comment_form = forms.CommentForm()
        
        context['comments'] = comments
        context['comment_form'] = comment_form
        return context
    
@login_required
def buy_now(request, id):
    car = models.Car.objects.get(pk=id)
    if car.quantity > 0:
        
        models.userPurchase.objects.create(
            author=request.user,
            car=car,
            quantity_purchased=1,
            total_price=car.price
        )

        car.quantity -= 1
        car.save()

       
    return redirect('car:car_details', id=id)

car_sales_website/car_sales_website/views.py
from django.shortcuts import render
from car.models import Car
from brand.models import Brand

def home(request,brand_slug = None):
    data = Car.objects.all()
    if brand_slug is not None:
        brand = Brand.objects.get(slug = brand_slug)
        data = Car.objects.filter(brand  = brand)
    brands = Brand.objects.all()
    return render(request, 'home.html', {'car' : data, 'brand' : brands})

car_sales_website/author/templates/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<form style="width:50% ; margin : auto" method="post">
    <h1>Change Your Password </h1>
    {% csrf_token %}
    {{form | crispy}}

    <button class="btn btn-danger rounded-0 mb-5">Submit</button>
</form>

{% endblock %}

car_sales_website/author/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div>
    <a class="btn btn-primary rounded-0 mt-3" href="{% url 'author:edit_profile' %}">
        Edit Your Profile</a>
</div>
<p class="text-center fw-bold fs-3">Order History</p>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4  mt-2 mb-5">
    {% for c in data %}
    <div class="col">
        <div class="card h-100 border-0 shadow py-3 ">
            <img src="{{c.car.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">


                <p class="card-title fw-bold">{{c.car.name}}</p>
                <p class="fw-bold mt-2 text-danger">$ {{c.total_price}}</p>
                <p>Quantity Purchased: {{c.quantity_purchased}}</p>
                <p><span class="fw-medium">Brand :</span> {{c.car.brand.name}}</a></p>
                <p class="card-text">{{c.car.description | truncatewords:10}}</p>
                <a href="{% url 'car:car_details' c.car.id %}" class="btn btn-dark rounded-0">View
                    Details</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}

car_sales_website/author/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<form style="width:50% ; margin : auto" method="post" novalidate class="lh-sm ">
    <h1>{{type}} Page</h1>
    {% csrf_token %}
    {% if form.non_field_errors %}
    {% for er in form.non_field_errors %}
    <p class="bg-danger text-white p-3">{{er}}</p>
    {% endfor %}
    {% endif %}
    <!-- {{form | crispy}} -->
    {% for fm in form%} {{fm.label_tag}} {{fm}} <small class="text-danger">
        <p>{{fm.errors|striptags}}</p>
    </small>
    {% endfor %}
    <button class="btn btn-danger rounded-0 mb-5" type="submit">{{type}}</button>
</form>

{% endblock %}

car_sales_website/author/templates/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<form style="width: 50%; margin: auto" method="post">
    <h1>Update Your Profile</h1>

    {% csrf_token %} {{form | crispy}}

    <button class="btn btn-danger rounded-0 mb-5" type="submit">Update</button>
    <p> <a class="btn btn-warning rounded-0 btn-sm" href="{% url 'author:pass_change' %}">Change Your Password</a></p>
</form>

{% endblock %}

car_sales_website/car/templates/car_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-12">
    <div class="card my-2">
        <div class="card-body row align-items-center">
            <div class="col-md-6 col-12">
                <img src="{{car.image.url}}" class="card-img-top" alt="...">
            </div>
            <div class="col-md-6 col-12">
                <h1 class="card-title">{{car.name}}</h1>
                <p class="card-text">{{car.description}}</p>
                {% if car.quantity == 0 %}
                <p class="fw-bolder text-danger">Out of Stock</p>
                {% else %}
                <p><span class="fw-bold">Quantity:</span> {{car.quantity}}</p>
                {% endif %}
                <p><span class="fw-bold">Price:</span> $ {{car.price}} </p>
                <p><span class="fw-bold">Brand:</span> {{car.brand.name}} </p>
                {% if user.is_authenticated %}
                {% if car.quantity == 0 %}
                <a class="btn btn-dark disabled rounded-0">Buy Now</a>
                {% else %}
                <a href="{% url 'car:buy_now' car.id %}" class="btn btn-dark rounded-0">Buy Now</a>
                {% endif %}
                {% else %}
                <a href="{% url 'author:login'%}" class="btn btn-primary rounded-0">Login to Purchase</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="card my-2">
    <h5 class="p-3">Total Comments : {{comments | length}}</h5>

    {% for comment in comments %}
    <div class="card-body border m-2">
        <p><b>{{comment.name}}</b> <small>at {{comment.created_on}}</small></p>
        <p>{{comment.body}}</p>
    </div>
    {% endfor %}

</div>
<div class="card my-2">
    <div class="card-body">
        <form method="post">
            <h1>Add Comment</h1>
            {% csrf_token %}
            {{comment_form | crispy}}

            <button class="btn btn-danger rounded-0" type="submit">Submit</button>
    </div>
</div>
{% endblock %}

car_sales_website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Mart</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-lg shadow-sm ">
        <div class=" container">
            <a class="navbar-brand text-danger fw-bold fs-4" href="{% url 'home' %}">CAR MART</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse gap-2 " id="navbarNavAltMarkup">
                <div class="navbar-nav  ps-lg-5 item-nav">
                    <a class="btn btn-outline-dark rounded-0 py-1" aria-current="page" href="{% url 'home' %}">Home</a>


                </div>
                <div class="navbar-nav  item-nav gap-2 ms-lg-auto 2">
                    {% if user.is_authenticated %}
                    <a href="{% url 'author:profile'%}" class="btn btn-primary rounded-0">Profile</a>
                    <form method="post" action="{% url 'author:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger rounded-0"> Logout</button>
                    </form>
                    {% else%}
                    <a href="{% url 'author:register' %}" class="btn btn-outline-danger rounded-0">Sign Up</a>
                    <a href="{% url 'author:login' %}" class="btn btn-danger rounded-0">Login</a>
                    {% endif %}
                    <!-- <a class="nav-link " aria-current="page" href="#">Add Task</a> -->
                    <!-- <a class="nav-link " aria-current="page" href="#">Show Tasks</a> -->

                </div>
            </div>
        </div>
    </nav>
    <section class="container ">
        {% block content %}
        {% endblock %}
    </section>






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

car_sales_website/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row  py-5">
    <div
        class="col-md-6 col-12 order-2 order-md-1 d-flex justify-content-center justify-content-lg-start align-items-center">
        <div class="me-0 ">
            <h2 class="fw-bolder fs-1">BUY YOUR <span class="text-danger ">Favourite</span> <br> <span
                    class="fw-medium">BRAND CAR</span></h2>
            <p>Let's start do your order now</p>
            <a class="text-decoration-none text-white bg-danger px-2 py-2 " href="#">Order
                Now</a>
        </div>
    </div>
    <div
        class="col-md-6 col-12 order-1 order-md-2 d-flex justify-content-center justify-content-lg-end  align-items-center ">
        <img src="{% static 'images/car.png' %}" alt="" class="w-75">
    </div>
</div>
<section>
    <div class="border border-1 border-dark p-3">
        <h3 class="">Brands</h3>
        <div class="mt-3 d-flex flex-wrap gap-3">
            <a href="{% url 'home'  %}" class="btn btn-outline-dark rounded-0 fw-medium px-2 py-1">ALL</a>
            {% for b in brand %}

            <a href="{% url 'brand_car' b.slug %}"
                class="btn btn-outline-dark rounded-0 fw-medium px-2 py-1">{{b.name}}</a>

            {% endfor %}
        </div>
    </div>
    <p class="text-center mt-3 fs-4 fw-medium">Total Cars : <span class="text-danger fw-bold">{{car | length}}</span>
    </p>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4  mt-2 mb-5">
        {% for c in car %}
        <div class="col">
            <div class="card h-100 border-0 shadow py-3 ">
                <img src="{{c.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">

                    <div class="d-flex justify-content-between align-items-center">
                        <p class="card-title fw-bold fs-4">{{c.name}}</p>
                        <p class="fw-bold mt-2 text-danger">$ {{c.price}}</p>
                    </div>
                    <p><span class="fw-medium">Brand :</span> {{c.brand.name}}</a></p>
                    <p class="card-text">{{c.description | truncatewords:10}}</p>
                    <a href="{% url 'car:car_details' c.id %}" class="btn btn-dark rounded-0">View
                        Details</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</section>
{% endblock %}